version: '3.8'

services:
  mongo:
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db
    command: mongod --replSet rs0 --oplogSize 128

  mongo-init:
    image: mongo:5.0
    depends_on:
      - mongo
    restart: on-failure
    command: mongosh --host mongo:27017 --eval "rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]})"

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    environment:
      PORT: 3000
      ROOT_URL: http://localhost:3000
      MONGO_URL: mongodb://mongo:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://mongo:27017/local?replicaSet=rs0
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - uploads:/app/uploads

volumes:
  mongodb_data:
  uploads:
